apiVersion: apps/v1
kind: Deployment
metadata:
    # annotations:
    #     io.rancher.container.pull_image: always
    #     kompose.cmd: ./migration-tools-0.1.3 parse --docker-file export/scanterra.PROD/kobotoolbox/docker-compose.yml
    #         --rancher-file export/scanterra.PROD/kobotoolbox/rancher-compose.yml --output-file
    #         parse2-kobotoolbox.PROD
    #     kompose.version: 1.21.0 (992df58d8)
    # creationTimestamp: null
    labels:
        io.kompose.service: db-backup
    name: db-backup
spec:
    replicas: 1
    selector:
        matchLabels:
            io.kompose.service: db-backup
    strategy:
        type: Recreate
    template:
        metadata:
            # annotations:
            #     io.rancher.container.pull_image: always
            #     kompose.cmd: ./migration-tools-0.1.3 parse --docker-file export/scanterra.PROD/kobotoolbox/docker-compose.yml
            #         --rancher-file export/scanterra.PROD/kobotoolbox/rancher-compose.yml
            #         --output-file parse2-kobotoolbox.PROD
            #     kompose.version: 1.21.0 (992df58d8)
            # creationTimestamp: null
            labels:
                io.kompose.service: db-backup
        spec:
            containers:
              - env:
                  - name: ARCHIVE_FILENAME
                    value: /backups/postgres_backup
                  - name: DUMPPREFIX
                    value: postgres_backup
                  - name: PGHOST
                    value: postgres
                  - name: PGPASSWORD
                    value: j3cA6eCIneo5nU5qjK8yXycaIu9B2l41
                  - name: PGPORT
                    value: "5432"
                  - name: PGUSER
                    value: kobo_superadmin
                  - name: POSTGRES_DBNAME
                    value: kobotoolbox
                  - name: POSTGRES_HOST
                    value: postgres
                  - name: POSTGRES_PASSWORD
                    value: j3cA6eCIneo5nU5qjK8yXycaIu9B2l41
                  - name: POSTGRES_PORT
                    value: "5432"
                  - name: POSTGRES_USER
                    value: kobo_superadmin
                  - name: WITH_POSTGIS
                    value: "1"
                image: scanterra/pg-backup:9.6
                imagePullPolicy: Always
                name: db-backup
                resources: {}
                volumeMounts:
                  - mountPath: /backups
                    name: kobotoolbox-backups-postgres
            restartPolicy: Always
            serviceAccountName: ""
            volumes:
              - name: kobotoolbox-backups-postgres
                persistentVolumeClaim:
                    claimName: kobotoolbox-backups-postgres
status: {}
