apiVersion: apps/v1
kind: Deployment
metadata:
    # annotations:
    #     io.rancher.container.pull_image: always
    #     kompose.cmd: ./migration-tools-0.1.3 parse --docker-file export/scanterra.PROD/kobotoolbox/docker-compose.yml
    #         --rancher-file export/scanterra.PROD/kobotoolbox/rancher-compose.yml --output-file
    #         parse2-kobotoolbox.PROD
    #     kompose.version: 1.21.0 (992df58d8)
    # creationTimestamp: null
    labels:
        io.kompose.service: mongo
    name: mongo
    namespace: kobotoolbox
spec:
    replicas: 1
    selector:
        matchLabels:
            io.kompose.service: mongo
    strategy:
        type: Recreate
    template:
        metadata:
            # annotations:
            #     io.rancher.container.pull_image: always
            #     kompose.cmd: ./migration-tools-0.1.3 parse --docker-file export/scanterra.PROD/kobotoolbox/docker-compose.yml
            #         --rancher-file export/scanterra.PROD/kobotoolbox/rancher-compose.yml
            #         --output-file parse2-kobotoolbox.PROD
            #     kompose.version: 1.21.0 (992df58d8)
            # creationTimestamp: null
            labels:
                io.kompose.service: mongo
        spec:
            containers:
              - env:
                  - name: CSRF_COOKIE_DOMAIN
                    value: .scanterra.com
                  - name: DJANGO_ALLOWED_HOSTS
                    value: .scanterra.com
                  - name: DJANGO_SECRET_KEY
                    value: '"nhjh^gy1l@w4*#l)v5-v&rx0g5zgx!-9uygf786u!f6k9hs6+2"'
                  - name: ENKETO_API_TOKEN
                    value: enketoapitoken
                  - name: ENKETO_EXPRESS_PUBLIC_SUBDOMAIN
                    value: local.scancollect-form
                  - name: ENKETO_SERVER_NAME
                    value: local.scancollect-form.scanterra.com
                  - name: ENKETO_URL
                    value: https://local.scancollect-form.scanterra.com
                  - name: KOBOCAT_MEDIA_BACKUP_SCHEDULE
                    value: '#0 0 * * 0'
                  - name: KOBOCAT_PUBLIC_SUBDOMAIN
                    value: local.scancollect
                  - name: KOBOCAT_SERVER_NAME
                    value: local.scancollect.scanterra.com
                  - name: KOBOCAT_URL
                    value: https://local.scancollect.scanterra.com
                  - name: KOBOFORM_PUBLIC_SUBDOMAIN
                    value: local.scancollect-form-edit
                  - name: KOBOFORM_SERVER_NAME
                    value: local.scancollect-form-edit.scanterra.com
                  - name: KOBOFORM_URL
                    value: https://local.scancollect-form-edit.scanterra.com
                  - name: KOBO_SUPERUSER_PASSWORD
                    value: HsBUDwh6#JwVpBR@VILU
                  - name: KOBO_SUPERUSER_USERNAME
                    value: kobo_superadmin
                  - name: KOBO_SUPPORT_EMAIL
                    value: soporte@scanterra.com
                  - name: MONGO_BACKUP_ARCHIVE_FILENAME
                    value: mongo_backup.mongorestore.tar.gz
                  - name: MONGO_BACKUP_SCHEDULE
                    value: 0 1 * * *
                  - name: MONGO_DATA
                    value: /srv/db
                  - name: POSTGRES_BACKUP_ARCHIVE_FILENAME
                    value: postgres_backup_kobotoolbox.pg_restore
                  - name: POSTGRES_BACKUP_SCHEDULE
                    value: '#0 2 * * 0'
                  - name: PUBLIC_DOMAIN_NAME
                    value: local.scanterra.com
                  - name: USE_ENV_VAR
                    value: "true"
                image: scanterra/kobotoolbox_mongo:latest
                imagePullPolicy: Always
                name: mongo
                resources: {}
                volumeMounts:
                  - mountPath: /srv/db
                    name: kobotoolbox-vols-mongo
                  - mountPath: /srv/backups
                    name: kobotoolbox-backups-mongo
            restartPolicy: Always
            serviceAccountName: ""
            volumes:
              - name: kobotoolbox-vols-mongo
                persistentVolumeClaim:
                    claimName: kobotoolbox-vols-mongo
              - name: kobotoolbox-backups-mongo
                persistentVolumeClaim:
                    claimName: kobotoolbox-backups-mongo
status: {}
