apiVersion: apps/v1
kind: Deployment
metadata:
    # annotations:
    #     io.rancher.container.pull_image: always
    #     kompose.cmd: ./migration-tools-0.1.3 parse --docker-file export/scanterra.PROD/kobotoolbox/docker-compose.yml
    #         --rancher-file export/scanterra.PROD/kobotoolbox/rancher-compose.yml --output-file
    #         parse2-kobotoolbox.PROD
    #     kompose.version: 1.21.0 (992df58d8)
    # creationTimestamp: null
    labels:
        io.kompose.service: mongo-btsync
    name: mongo-btsync
spec:
    replicas: 1
    selector:
        matchLabels:
            io.kompose.service: mongo-btsync
    strategy:
        type: Recreate
    template:
        metadata:
            # annotations:
            #     io.rancher.container.pull_image: always
            #     kompose.cmd: ./migration-tools-0.1.3 parse --docker-file export/scanterra.PROD/kobotoolbox/docker-compose.yml
            #         --rancher-file export/scanterra.PROD/kobotoolbox/rancher-compose.yml
            #         --output-file parse2-kobotoolbox.PROD
            #     kompose.version: 1.21.0 (992df58d8)
            # creationTimestamp: null
            labels:
                io.kompose.service: mongo-btsync
        spec:
            containers:
              - env:
                  - name: DEVICE
                    value: ScanTerra Production - Mongo
                  - name: SECRET
                    value: ATCAWOQEHQJIGF6SLXUBL3BE6D2ZP3JF7
                  - name: STANDBY_MODE
                    value: "TRUE"
                image: scanterra/btsync:rancher
                imagePullPolicy: Always
                name: mongo-btsync
                resources: {}
                stdin: true
                tty: true
                volumeMounts:
                  - mountPath: /web
                    name: kobotoolbox-backups-mongo
            imagePullSecrets:
              - name: dockerhub
            restartPolicy: Always
            serviceAccountName: ""
            volumes:
              - name: kobotoolbox-backups-mongo
                persistentVolumeClaim:
                    claimName: kobotoolbox-backups-mongo
status: {}
