apiVersion: apps/v1
kind: Deployment
metadata:
    # annotations:
    #     io.rancher.container.pull_image: always
    #     kompose.cmd: ./migration-tools-0.1.3 parse --docker-file export/scanterra.PROD/kobotoolbox/docker-compose.yml
    #         --rancher-file export/scanterra.PROD/kobotoolbox/rancher-compose.yml --output-file
    #         parse2-kobotoolbox.PROD
    #     kompose.version: 1.21.0 (992df58d8)
    # creationTimestamp: null
    labels:
        io.kompose.service: postgres
    name: postgres
spec:
    replicas: 1
    selector:
        matchLabels:
            io.kompose.service: postgres
    strategy:
        type: Recreate
    template:
        metadata:
            # annotations:
            #     io.rancher.container.pull_image: always
            #     kompose.cmd: ./migration-tools-0.1.3 parse --docker-file export/scanterra.PROD/kobotoolbox/docker-compose.yml
            #         --rancher-file export/scanterra.PROD/kobotoolbox/rancher-compose.yml
            #         --output-file parse2-kobotoolbox.PROD
            #     kompose.version: 1.21.0 (992df58d8)
            # creationTimestamp: null
            labels:
                io.kompose.service: postgres
        spec:
            containers:
              - env:
                  - name: ALLOW_IP_RANGE
                    value: 0.0.0.0/0
                  - name: POSTGRES_DBNAME
                    value: kobotoolbox
                  - name: POSTGRES_PASSWORD
                    value: j3cA6eCIneo5nU5qjK8yXycaIu9B2l41
                  - name: POSTGRES_USER
                    value: kobo_superadmin
                image: scanterra/postgis:9.6-2.4
                imagePullPolicy: Always
                name: postgres
                resources: {}
                volumeMounts:
                  - mountPath: /var/lib/postgresql
                    name: kobotoolbox-vols-db
                  - mountPath: /srv/backups
                    name: kobotoolbox-backups-postgres
            imagePullSecrets:
              - name: dockerhub
            restartPolicy: Always
            serviceAccountName: ""
            volumes:
              - name: kobotoolbox-vols-db
                persistentVolumeClaim:
                    claimName: kobotoolbox-vols-db
              - name: kobotoolbox-backups-postgres
                persistentVolumeClaim:
                    claimName: kobotoolbox-backups-postgres
status: {}
