apiVersion: apps/v1
kind: Deployment
metadata:
    # annotations:
    #     io.rancher.container.pull_image: always
    #     kompose.cmd: ./migration-tools-0.1.3 parse --docker-file export/scanterra.PROD/kobotoolbox/docker-compose.yml
    #         --rancher-file export/scanterra.PROD/kobotoolbox/rancher-compose.yml --output-file
    #         parse2-kobotoolbox.PROD
    #     kompose.version: 1.21.0 (992df58d8)
    # creationTimestamp: null
    labels:
        io.kompose.service: rabbit
    name: rabbit
    namespace: kobotoolbox
spec:
    replicas: 1
    selector:
        matchLabels:
            io.kompose.service: rabbit
    strategy:
        type: Recreate
    template:
        metadata:
            # annotations:
            #     io.rancher.container.pull_image: always
            #     kompose.cmd: ./migration-tools-0.1.3 parse --docker-file export/scanterra.PROD/kobotoolbox/docker-compose.yml
            #         --rancher-file export/scanterra.PROD/kobotoolbox/rancher-compose.yml
            #         --output-file parse2-kobotoolbox.PROD
            #     kompose.version: 1.21.0 (992df58d8)
            # creationTimestamp: null
            labels:
                io.kompose.service: rabbit
        spec:
            containers:
              - env:
                  - name: RABBITMQ_LOG_BASE
                    value: /var/log/rabbitmq
                image: scanterra/kobotoolbox_rabbit:latest
                imagePullPolicy: Always
                name: rabbit
                resources: {}
                volumeMounts:
                  - mountPath: /var/log/rabbitmq
                    name: kobotoolbox-log-rabbitmq
            restartPolicy: Always
            serviceAccountName: ""
            volumes:
              - name: kobotoolbox-log-rabbitmq
                persistentVolumeClaim:
                    claimName: kobotoolbox-log-rabbitmq
status: {}
