apiVersion: apps/v1
kind: Deployment
metadata:
    # annotations:
    #     io.rancher.container.pull_image: always
    #     kompose.cmd: ./migration-tools-0.1.3 parse --docker-file export/scanterra.PROD/kobotoolbox/docker-compose.yml
    #         --rancher-file export/scanterra.PROD/kobotoolbox/rancher-compose.yml --output-file
    #         parse2-kobotoolbox.PROD
    #     kompose.version: 1.21.0 (992df58d8)
    # creationTimestamp: null
    labels:
        io.kompose.service: redis-cache
    name: redis-cache
    namespace: kobotoolbox
spec:
    replicas: 1
    selector:
        matchLabels:
            io.kompose.service: redis-cache
    strategy: {}
    template:
        metadata:
            # annotations:
            #     io.rancher.container.pull_image: always
            #     kompose.cmd: ./migration-tools-0.1.3 parse --docker-file export/scanterra.PROD/kobotoolbox/docker-compose.yml
            #         --rancher-file export/scanterra.PROD/kobotoolbox/rancher-compose.yml
            #         --output-file parse2-kobotoolbox.PROD
            #     kompose.version: 1.21.0 (992df58d8)
            # creationTimestamp: null
            labels:
                io.kompose.service: redis-cache
        spec:
            containers:
              - image: scanterra/kobotoolbox_redis_cache:2.6
                imagePullPolicy: Always
                name: redis-cache
                resources: {}
            restartPolicy: Always
            serviceAccountName: ""
            volumes: null
status: {}
