apiVersion: v1
kind: PersistentVolume
metadata:
  name: kobotoolbox-vols-mongo
spec:
  storageClassName: manual
  capacity:
    storage: 100Mi
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: /var/lib/tmp/kobotoolbox-vols-mongo
    type: DirectoryOrCreate
