apiVersion: v1
kind: PersistentVolume
metadata:
    name: kobotoolbox-backups-postgres
spec:
    storageClassName: manual
    capacity:
        storage: 100Mi
    accessModes:
      - ReadWriteOnce
    hostPath:
        path: /var/lib/tmp/kobotoolbox-backups-postgres
        type: DirectoryOrCreate
