apiVersion: v1
kind: Service
metadata:
    labels:
        io.kompose.service: db-backup
    name: db-backup
spec:
    selector:
        io.kompose.service: db-backup
    ports:
      - name: "5432"
        port: 5432
        targetPort: 5432
status: {}
