apiVersion: v1
kind: Service
metadata:
    labels:
        io.kompose.service: mongo-btsync
    name: mongo-btsync
    namespace: kobotoolbox
spec:
    selector:
        io.kompose.service: mongo-btsync
status: {}
