apiVersion: v1
kind: Service
metadata:
    labels:
        io.kompose.service: mongo
    name: mongo
    namespace: kobotoolbox
spec:
    selector:
        io.kompose.service: mongo
    ports:
      - name: "27017"
        port: 27017
        targetPort: 27017
status: {}
