apiVersion: v1
kind: Service
metadata:
    labels:
        io.kompose.service: postgres
    name: postgres
    namespace: kobotoolbox
spec:
    selector:
        io.kompose.service: postgres
    ports:
      - name: "5432"
        port: 5432
        targetPort: 5432
status: {}
