apiVersion: v1
kind: Service
metadata:
    labels:
        io.kompose.service: rabbit
    name: rabbit
    namespace: kobotoolbox
spec:
    selector:
        io.kompose.service: rabbit
    ports:
      - name: "5672"
        port: 5672
        targetPort: 5672
status: {}
