apiVersion: v1
kind: Service
metadata:
    labels:
        io.kompose.service: redis-cache
    name: redis-cache
spec:
    selector:
        io.kompose.service: redis-cache
    ports:
      - name: "6379"
        port: 6379
        targetPort: 6379
status: {}
