apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    # creationTimestamp: null
    # labels:
    #     io.kompose.service: kobotoolbox-vols-redismaindata
    name: kobotoolbox-vols-redismaindata
spec:
    storageClassName: manual
    volumeName: kobotoolbox-vols-redismaindata
    accessModes:
      - ReadWriteOnce
    resources:
        requests:
            storage: 100Mi
status: {}
