apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    # creationTimestamp: null
    # labels:
    #     io.kompose.service: kobotoolbox-vols-db
    name: kobotoolbox-vols-db
spec:
    storageClassName: manual
    volumeName: kobotoolbox-vols-db
    accessModes:
      - ReadWriteOnce
    resources:
        requests:
            storage: 1Gi
status: {}
