{{ range $idx, $deployment := .Values.deployments }}
{{- if $deployment.deploy }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: {{ $idx }}
  name: {{ $idx }}
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: {{ $idx }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.kompose.service: {{ $idx }}
    spec:
      {{- if not (empty $deployment.initContainers) }}
      initContainers:
        {{- with $deployment.initContainers }}
          {{- toYaml . | trim | nindent 6 }}
        {{- end }}
      {{- end }}
      containers:
      - name: {{ $idx }}
        image: {{ $deployment.image }}
        imagePullPolicy: {{ $.Values.imagePullPolicy }}
        {{- if not (empty $deployment.envs) }}
        env:
          {{- if has $idx (list "nginx" "kpi" "kobocat" "enketo-express") }}
            {{ template "common-envs" $.Values }}
          {{- end }}
          {{- $specificEnvs := set $.Values "name" $idx }}
          {{- template "specific-envs" $specificEnvs }}
        {{- end }}
        {{- if not (empty $deployment.volumes) }}
          {{- include "volumeMounts" $deployment | trim | nindent 8 }}
        {{- end}}
      imagePullSecrets:
        - name: {{ $.Values.imagePullSecrets }}
      restartPolicy: {{ $.Values.restartPolicy }}
      serviceAccountName: ""
      {{- include "volumes" $deployment | trim | nindent 6 }}
status: {}
{{- end }}
{{ end }}
