{{ range $idx, $service := .Values.services }}
{{- if $service.deploy }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: {{ $idx }}
  name: {{ $idx }}
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: {{ $idx }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.kompose.service: {{ $idx }}
    spec:
      containers:
      - name: {{ $idx }}
        image: {{ $service.image }}
        imagePullPolicy: {{ $.Values.imagePullPolicy }}
        {{- if not (empty $service.envs) }}
        env:
          {{- if has $idx (list "nginx" "kpi" "kobocat" "enketo-express") }}
            {{ template "common-envs" $.Values }}
          {{- end }}
          {{- $specificEnvs := set $.Values "name" $idx }}
          {{- template "specific-envs" $specificEnvs }}
        {{- end }}
        {{- if not (empty .volumes) }}
        volumeMounts:
          {{- with .volumes }}
            {{- range $idx, $val := .}}
          - mountPath: {{ $val }}
            name: {{ $idx }}
            {{- end }}
          {{- end }}
        {{- end }}
      imagePullSecrets:
        - name: {{ $.Values.imagePullSecrets }}
      restartPolicy: {{ $.Values.restartPolicy }}
      serviceAccountName: ""
      {{- if not (empty .volumes) }}
      volumes:
        {{- with $service.volumes }}
            {{- range $idx, $val := .}}
        - name: {{ $idx }}
          persistentVolumeClaim:
            claimName: {{ $idx }}
            {{- end }}
        {{- end }}
      {{- end }}
status: {}
{{- end }}
{{ end }}
