{{ range $idx, $service := .Values.services }}
{{- if $service.deploy }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: {{ $idx }}
  name: {{ $idx }}
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: {{ $idx }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.kompose.service: {{ $idx }}
    spec:
      {{- if not (empty .initContainers) }}
      initContainers:
        {{- with .initContainers }}
          {{- toYaml . | trim | nindent 8 }}
        {{- end }}
      {{- end }}
      containers:
      - name: {{ $idx }}
        image: {{ $service.image }}
        imagePullPolicy: {{ $.Values.imagePullPolicy }}
        env:
        {{- if eq $idx "smtp" }}
          - name: maildomain
            value: {{ $.Values.PUBLIC_DOMAIN_NAME}}
          - name: smtp_user
            value: {{ $.Values.EMAIL_HOST_USER }}:{{ $.Values.EMAIL_HOST_PASSWORD }}
        {{- end }}
        {{- if eq $idx "rabbit" }}
          - name: RABBITMQ_LOG_BASE
            value: /var/log/rabbitmq
        {{- end }}
        {{- if eq $idx "db-backup" }}
          - name: ARCHIVE_FILENAME
            value: {{ $.Values.ARCHIVE_FILENAME }}
          - name: DUMPPREFIX
            value: {{ $.Values.DUMPPREFIX }}
          - name: PGHOST
            value: {{ $.Values.POSTRES_HOST }}
          - name: PGPASSWORD
            value: {{ $.Values.POSTGRES_PASSWORD }}
          - name: PGPORT
            value: {{ $.Values.POSTRES_PORT }}
          - name: PGUSER
            value: {{ $.Values.POSTGRES_USER }}
          - name: POSTGRES_DBNAME
            value: {{ $.Values.POSTGRES_DBNAME }}
          - name: POSTGRES_HOST
            value: {{ $.Values.POSTRES_HOST }}
          - name: POSTGRES_PASSWORD
            value: {{ $.Values.POSTGRES_PASSWORD }}
          - name: POSTGRES_PORT
            value: {{ $.Values.POSTRES_PORT }}
          - name: POSTGRES_USER
            value: {{ $.Values.POSTGRES_USER }}
          - name: WITH_POSTGIS
            value: "1"
        {{- end }}
        {{- if eq $idx "postgres" }}
          - name: ALLOW_IP_RANGE
            value: 0.0.0.0/0
          - name: POSTGRES_DBNAME
            value: {{ $.Values.POSTGRES_DBNAME }}
          - name: POSTGRES_PASSWORD
            value: {{ $.Values.POSTGRES_PASSWORD }}
          - name: POSTGRES_USER
            value: {{ $.Values.POSTGRES_USER }}
        {{- end }}
        {{- if eq $idx "mongo" }}
          - name: MONGO_BACKUP_ARCHIVE_FILENAME
            value: {{ $.Values.MONGO_BACKUP_ARCHIVE_FILENAME }}
          - name: MONGO_BACKUP_SCHEDULE
            value: {{ $.Values.MONGO_BACKUP_SCHEDULE }}
            MONGO_BACKUP_SCHEDULE: 0 1 * * *
          - name: MONGO_DATA
            value: {{ $.Values.MONGO_DATA }}
          - name: POSTGRES_BACKUP_ARCHIVE_FILENAME
            value: {{ $.Values.POSTGRES_BACKUP_ARCHIVE_FILENAME }}
          - name: POSTGRES_BACKUP_SCHEDULE
            value: {{ $.Values.POSTGRES_BACKUP_SCHEDULE }}
        {{- end }}
        {{- if eq $idx "borg-backup-service" }}
          - name: ARCHIVE_PREFIX
            value: kobotoolbox
          - name: BACKUP_FROM
            value: /borg/data
          - name: BACKUP_WHAT
            value: .
          - name: BORG_PASSPHRASE
            value: {{ $.Values.BORG_PASSPHRASE }}
          - name: BORG_REPO
            value: /borg/repo
          - name: COMPRESSION
            value: lz4
          - name: KEEP_DAILY
            value: "7"
          - name: KEEP_MONTHLY
            value: "12"
          - name: KEEP_WEEKLY
            value: "4"
          - name: KEEP_YEARLY
            value: "1"
          - name: PRUNE
            value: "1"
        {{- end }}
        {{- if eq $idx "borg-backup-service-server" }}
          - name: ARCHIVE_PREFIX
            value: kobotoolbox
          - name: BORG_PASSPHRASE
            value: {{ $.Values.BORG_PASSPHRASE }}
          - name: BORG_RELOCATED_REPO_ACCESS_IS_OK
            value: "yes"
          - name: BORG_REPO
            value: /borg/repo
          - name: USERS
            value: root
        {{- end }}

        {{- if not (empty .volumes) }}
        volumeMounts:
          {{- with .volumes }}
            {{- range $idx, $val := .}}
          - mountPath: {{ $val }}
            name: {{ $idx }}
            {{- end }}
          {{- end }}
        {{- end }}                
      imagePullSecrets:
        - name: {{ $.Values.imagePullSecrets }}
      restartPolicy: {{ $.Values.restartPolicy }}
      serviceAccountName: ""
      {{- if not (empty .volumes) }}
      volumes:
        {{- with $service.volumes }}
            {{- range $idx, $val := .}}
        - name: {{ $idx }}
          persistentVolumeClaim:
            claimName: {{ $idx }}
            {{- end }}
        {{- end }}
      {{- end }}
status: {}
{{- end }}
{{ end }}
