{{ range $idx, $deployment := .Values.deployments }}
{{- if and (not (empty $deployment.ports)) $deployment.deploy }}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: {{ $idx }}
  name: {{ $idx }}
spec:
  selector:
    io.kompose.service: {{ $idx }}
  ports:
    {{- with $deployment.ports }}
      {{- range $idx, $val := .}}
    - name: {{ $idx }}
      port: {{ $val }}
      targetPort: {{ $val }}
      {{- end }}
    {{- end }}
{{- end }}
{{ end }}
