{{ range $idx, $size := .Values.volumeClaims }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ $idx }}
spec:
  storageClassName: {{ $.Values.storageClass }}
  volumeName: {{ $idx }}
  accessModes:
    - {{ $.Values.accessMode }}
  resources:
    requests:
      storage: {{ $size }}
{{ end }}
